### ISSUE TITLE
value error on time

### ISSUE THREAD

**Issue by abovethetime1** [ClementRoyer/TwitchAFK#16]
![error](https://user-images.githubusercontent.com/76911106/103482232-06cf4180-4e23-11eb-99b1-72cfb11c8fdd.png)
getting this error when betting is found.

**Comment by ClementRoyer** [comment]
Hi, thank you for reporting this issue. I will try to look at it ASAP

**Comment by abovethetime1** [comment]
thank you!

**Comment by mudachyo** [comment]
Most likely, this error occurs due to the fact that the language on Twitch should be French
![image](https://user-images.githubusercontent.com/25475399/103483201-b346fe80-4df6-11eb-8a17-fcb173ab05f6.png)

**Comment by ClementRoyer** [comment]
> Most likely, this error occurs due to the fact that the language on Twitch should be French
> ![image](https://user-images.githubusercontent.com/25475399/103483201-b346fe80-4df6-11eb-8a17-fcb173ab05f6.png)

Could be, but should be accessible to every language

**Comment by ClementRoyer** [comment]
Should be fixed by [commit d9aa198](https://github.com/ClementRoyer/TwitchAutoCollect-AutoBet/commit/d9aa198c1f502bf935f825d31d6b0f138ce133a5).

If it happens again after you pulled, pls reopen this issue.


@abovethetime1, Thank you for reporting this issue! 
@mudachyo, Thank you for your investigation, I appreciate the help!
